use uuid::Uuid;

/// A per-request identifier, generated by [`TraceLayer`](crate::TraceLayer) and
/// stored in the request's [`http::Extensions`]. Handlers read it back with the
/// framework's extension mechanism (e.g. axum's `Extension<RequestId>` after the
/// layer, or `req.extensions().get::<RequestId>()`).
#[derive(Clone, Copy, Debug)]
pub struct RequestId(Uuid);

impl RequestId {
    pub(crate) fn generate() -> Self {
        Self(Uuid::new_v4())
    }
}

impl std::ops::Deref for RequestId {
    type Target = Uuid;

    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

impl From<RequestId> for Uuid {
    fn from(r: RequestId) -> Self {
        r.0
    }
}

impl std::fmt::Display for RequestId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.0)
    }
}
